apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-postgres-0
  namespace: taskhub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi



