apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskhub
type: Opaque
data:
  POSTGRES_DB: dGFza2h1Yg==        # taskhub
  POSTGRES_USER: dGFzaHVidXNlcg==  # taskhubuser
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
