apiVersion: v1
kind: Secret
metadata:
  name: taskhub-db-secret
  namespace: taskhub
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: taskhub
  DB_USER: taskhubuser
  DB_PASSWORD: password

